name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download everything
      run: make

    - name: List everything
      run: ls -lh
      
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: .
